import { useEffect, useRef, useState } from 'react';
import { ActivityIndicator, Modal, Pressable, StyleSheet, Text, View } from 'react-native';
import { WebView } from 'react-native-webview';
import { captchaApi, type GeetestRegister } from '../api/captcha';
import { setCaptchaHandler, type CaptchaFields } from '../api/client';
import { colors } from '../theme';

type Pending = { resolve: (value: CaptchaFields | null) => void };

export function CaptchaProvider({children}:{children:React.ReactNode}) {
  const pending = useRef<Pending|null>(null); const sceneRef=useRef('global'); const kindRef=useRef<'geetest'|'hcaptcha'>('geetest'); const [visible,setVisible]=useState(false); const [html,setHtml]=useState(''); const [error,setError]=useState('');
  useEffect(()=>{setCaptchaHandler(async (scene,kind)=>{try{sceneRef.current=scene;kindRef.current=kind;setError('');if(kind==='hcaptcha'){const config=await captchaApi.hcaptchaConfig();if(!config.enabled||!config.site_key)return null;await captchaApi.hcaptchaShow(scene).catch(()=>null);setHtml(buildHcaptchaHtml(config.site_key));}else{const config=await captchaApi.config();if(!config.enabled||!config.scenes[scene])return null;await captchaApi.show(scene).catch(()=>null);const registration=await captchaApi.register();setHtml(buildHtml(registration,config.product||'popup'));}setVisible(true);return await new Promise<CaptchaFields|null>(resolve=>{pending.current={resolve}});}catch(e){setError(e instanceof Error?e.message:'验证码加载失败');setVisible(true);return await new Promise<CaptchaFields|null>(resolve=>{pending.current={resolve}});}});return()=>setCaptchaHandler(null)},[]);
  const close=(value:CaptchaFields|null)=>{setVisible(false);setHtml('');pending.current?.resolve(value);pending.current=null};
  const receive=async(raw:string)=>{try{const data=JSON.parse(raw);if(data.type==='hcaptcha'){await captchaApi.hcaptchaVerify(data.token,sceneRef.current);close({});}else if(data.type==='success')close(data.payload);else if(data.type==='error')setError(data.message||'验证加载失败')}catch(e){setError(e instanceof Error?e.message:'验证失败，请重试')}};
  return <>{children}<Modal visible={visible} transparent animationType="fade" onRequestClose={()=>close(null)}><View style={styles.overlay}><View style={styles.card}><View style={styles.header}><Text style={styles.title}>安全验证</Text><Pressable onPress={()=>close(null)}><Text style={styles.close}>取消</Text></Pressable></View>{error?<View style={styles.center}><Text style={styles.error}>{error}</Text></View>:html?<WebView originWhitelist={['*']} source={{html}} javaScriptEnabled domStorageEnabled thirdPartyCookiesEnabled sharedCookiesEnabled style={styles.web} onMessage={event=>void receive(event.nativeEvent.data)}/>:<View style={styles.center}><ActivityIndicator color={colors.ink}/></View>}</View></View></Modal></>;
}
function buildHtml(data:GeetestRegister,product:string){const payload=JSON.stringify({...data,product}).replace(/</g,'\\u003c');return `<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{margin:0;padding:20px;font-family:sans-serif}#captcha{min-height:48px}</style><script src="https://static.geetest.com/static/js/gt.0.5.0.js"></script></head><body><div id="captcha"></div><script>const cfg=${payload};function send(v){window.ReactNativeWebView.postMessage(JSON.stringify(v))}initGeetest({gt:cfg.gt,challenge:cfg.challenge,offline:!cfg.success,new_captcha:cfg.new_captcha,product:cfg.product,width:'100%'},function(c){c.onReady(function(){if(cfg.product==='bind')c.verify()});c.onSuccess(function(){const r=c.getValidate();send({type:'success',payload:{geetest_challenge:r.geetest_challenge,geetest_validate:r.geetest_validate,geetest_seccode:r.geetest_seccode}})});c.onError(function(){send({type:'error',message:'验证码加载出错'})});if(cfg.product!=='bind')c.appendTo('#captcha')});</script></body></html>`}
function buildHcaptchaHtml(siteKey:string){const key=JSON.stringify(siteKey).replace(/</g,'\\u003c');return `<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{margin:0;padding:24px;display:flex;justify-content:center}</style><script src="https://js.hcaptcha.com/1/api.js" async defer></script></head><body><div class="h-captcha" data-sitekey=${key} data-callback="done" data-error-callback="failed"></div><script>function done(token){window.ReactNativeWebView.postMessage(JSON.stringify({type:'hcaptcha',token:token}))}function failed(){window.ReactNativeWebView.postMessage(JSON.stringify({type:'error',message:'hCaptcha 验证失败'}))}</script></body></html>`}
const styles=StyleSheet.create({overlay:{flex:1,padding:20,alignItems:'center',justifyContent:'center',backgroundColor:'rgba(10,18,30,.45)'},card:{width:'100%',maxWidth:420,height:300,overflow:'hidden',borderRadius:22,backgroundColor:colors.surface},header:{height:54,paddingHorizontal:18,flexDirection:'row',alignItems:'center',justifyContent:'space-between',borderBottomWidth:1,borderColor:colors.border},title:{fontSize:16,fontWeight:'900',color:colors.ink},close:{fontSize:13,fontWeight:'800',color:colors.muted},web:{flex:1,backgroundColor:colors.surface},center:{flex:1,alignItems:'center',justifyContent:'center',padding:20},error:{textAlign:'center',color:colors.danger}});
