import { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, FlatList, Image, Pressable, RefreshControl, StyleSheet, Text, View } from 'react-native';
import type { NativeStackScreenProps } from '@react-navigation/native-stack';
import { resolveAssetUrl } from '../api/client';
import { userApi } from '../api/user';
import { colors } from '../theme';
import type { RootStackParamList } from '../types/navigation';
import type { PublicUser } from '../types/user';

export function ConnectionsScreen({route,navigation}:NativeStackScreenProps<RootStackParamList,'Connections'>){const {codemaoId,mode}=route.params;const [items,setItems]=useState<PublicUser[]>([]);const [loading,setLoading]=useState(true);const [refreshing,setRefreshing]=useState(false);const [error,setError]=useState('');const load=useCallback(async()=>{try{setError('');const data=mode==='followers'?await userApi.followers(codemaoId):await userApi.following(codemaoId);setItems(data.list||[]);}catch(e){setError(e instanceof Error?e.message:'加载失败');}finally{setLoading(false);setRefreshing(false);}},[codemaoId,mode]);useEffect(()=>{void load()},[load]);if(loading)return <View style={styles.center}><ActivityIndicator color={colors.ink}/></View>;return <FlatList data={items} keyExtractor={(u)=>String(u.codemao_user_id)} contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>{setRefreshing(true);void load()}}/>} ListHeaderComponent={error?<Text style={styles.error}>{error}</Text>:null} ListEmptyComponent={<Text style={styles.empty}>这里还没有用户</Text>} renderItem={({item})=>{const avatar=resolveAssetUrl(item.avatar);const name=item.nickname||item.username;return <Pressable style={styles.user} onPress={()=>item.codemao_user_id&&navigation.push('UserProfile',{codemaoId:String(item.codemao_user_id)})}>{avatar?<Image source={{uri:avatar}} style={styles.avatar}/>:<View style={styles.avatarEmpty}><Text style={styles.initial}>{name.slice(0,1)}</Text></View>}<View style={{flex:1}}><Text style={styles.name}>{name}</Text><Text numberOfLines={1} style={styles.bio}>{item.bio||`${item.work_count||0} 个作品 · ${item.follower_count||0} 位粉丝`}</Text></View></Pressable>}}/>}
const styles=StyleSheet.create({center:{flex:1,alignItems:'center',justifyContent:'center'},content:{padding:16,flexGrow:1},user:{padding:13,marginBottom:10,flexDirection:'row',alignItems:'center',gap:12,borderRadius:17,backgroundColor:colors.surface},avatar:{width:48,height:48,borderRadius:15},avatarEmpty:{width:48,height:48,alignItems:'center',justifyContent:'center',borderRadius:15,backgroundColor:colors.ink},initial:{fontWeight:'900',color:'#fff'},name:{fontSize:14,fontWeight:'900',color:colors.ink},bio:{marginTop:4,fontSize:11,color:colors.muted},error:{marginBottom:12,color:colors.danger},empty:{padding:60,textAlign:'center',color:colors.subtle}});
