import { useEffect, useState } from 'react';
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Text, TextInput } from 'react-native';
import type { NativeStackScreenProps } from '@react-navigation/native-stack';
import { communityApi } from '../api/community';
import { colors } from '../theme';
import type { RootStackParamList } from '../types/navigation';

export function EditPostScreen({route,navigation}:NativeStackScreenProps<RootStackParamList,'EditPost'>){const [title,setTitle]=useState('');const [content,setContent]=useState('');const [category,setCategory]=useState('discussion');const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);useEffect(()=>{void communityApi.post(route.params.id).then(p=>{setTitle(p.title);setContent(p.content);setCategory(p.category||'discussion')}).catch(e=>Alert.alert('加载失败',e instanceof Error?e.message:'请稍后重试')).finally(()=>setLoading(false))},[route.params.id]);const save=async()=>{if(!title.trim()||!content.trim())return Alert.alert('请填写标题和正文');setSaving(true);try{await communityApi.updatePost(route.params.id,{title:title.trim(),content:content.trim(),category});Alert.alert('帖子已更新','',[{text:'完成',onPress:()=>navigation.goBack()}])}catch(e){Alert.alert('保存失败',e instanceof Error?e.message:'请稍后重试')}finally{setSaving(false)}};if(loading)return <ActivityIndicator style={{flex:1}} color={colors.ink}/>;return <ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={styles.content}><Text style={styles.label}>标题</Text><TextInput value={title} onChangeText={setTitle} maxLength={100} style={styles.input}/><Text style={styles.label}>正文</Text><TextInput value={content} onChangeText={setContent} multiline maxLength={10000} style={[styles.input,styles.body]}/><Pressable disabled={saving} onPress={()=>void save()} style={styles.save}>{saving?<ActivityIndicator color={colors.ink}/>:<Text style={styles.saveText}>保存修改</Text>}</Pressable></ScrollView>}
const styles=StyleSheet.create({content:{padding:18},label:{marginBottom:8,fontWeight:'800',color:colors.ink},input:{minHeight:48,marginBottom:18,padding:13,borderWidth:1,borderColor:colors.border,borderRadius:14,backgroundColor:colors.surface,color:colors.ink},body:{height:260,textAlignVertical:'top'},save:{height:50,alignItems:'center',justifyContent:'center',borderRadius:15,backgroundColor:colors.primary},saveText:{fontWeight:'900',color:colors.ink}});
