import { useCallback, useEffect, useState } from 'react';
import { Alert, FlatList, Pressable, RefreshControl, StyleSheet, Text, View } from 'react-native';
import type { NativeStackScreenProps } from '@react-navigation/native-stack';
import { communityApi } from '../api/community';
import { StateView } from '../components/StateView';
import { colors } from '../theme';
import type { Post } from '../types/community';
import type { RootStackParamList } from '../types/navigation';

export function MyPostsScreen({navigation}:NativeStackScreenProps<RootStackParamList,'MyPosts'>){const [items,setItems]=useState<Post[]>([]);const [loading,setLoading]=useState(true);const [refreshing,setRefreshing]=useState(false);const [error,setError]=useState('');const load=useCallback(async()=>{try{setError('');setItems((await communityApi.myPosts()).list||[])}catch(e){setError(e instanceof Error?e.message:'加载失败')}finally{setLoading(false);setRefreshing(false)}},[]);useEffect(()=>{void load()},[load]);const remove=(post:Post)=>Alert.alert('删除帖子',`确定删除“${post.title}”吗？`,[{text:'取消',style:'cancel'},{text:'删除',style:'destructive',onPress:async()=>{try{await communityApi.deletePost(post.id);setItems(v=>v.filter(x=>x.id!==post.id))}catch(e){Alert.alert('删除失败',e instanceof Error?e.message:'请稍后重试')}}}]);if(loading)return <StateView loading title="正在加载帖子"/>;if(error&&!items.length)return <StateView title="帖子加载失败" message={error} actionLabel="重试" onAction={()=>void load()}/>;return <FlatList data={items} keyExtractor={p=>String(p.id)} contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>{setRefreshing(true);void load()}}/>} ListEmptyComponent={<Text style={styles.empty}>还没有发布帖子</Text>} renderItem={({item})=><Pressable style={styles.item} onPress={()=>navigation.navigate('PostDetail',{id:item.id,title:item.title})}><Text numberOfLines={2} style={styles.title}>{item.title}</Text><Text style={styles.meta}>{item.category||'讨论'} · {item.comment_count||item.reply_count||0} 条回复</Text><View style={styles.actions}><Pressable onPress={()=>navigation.navigate('EditPost',{id:item.id})}><Text style={styles.edit}>编辑</Text></Pressable><Pressable onPress={()=>remove(item)}><Text style={styles.delete}>删除</Text></Pressable></View></Pressable>}/>}
const styles=StyleSheet.create({content:{padding:16,flexGrow:1},item:{marginBottom:11,padding:16,borderRadius:18,backgroundColor:colors.surface},title:{fontSize:16,lineHeight:23,fontWeight:'900',color:colors.ink},meta:{marginTop:8,fontSize:11,color:colors.subtle},actions:{marginTop:14,flexDirection:'row',gap:22},edit:{fontSize:12,fontWeight:'800',color:colors.ink},delete:{fontSize:12,fontWeight:'800',color:colors.danger},empty:{padding:60,textAlign:'center',color:colors.subtle}});
