import { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, Alert, Image, Linking, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import type { NativeStackScreenProps } from '@react-navigation/native-stack';
import { resolveAssetUrl } from '../api/client';
import { oauthApi, type OAuthAuthorizeInfo, type OAuthParams } from '../api/oauth';
import { useSession } from '../session/SessionContext';
import { colors } from '../theme';
import type { RootStackParamList } from '../types/navigation';

export function OAuthAuthorizeScreen({route,navigation}:NativeStackScreenProps<RootStackParamList,'OAuthAuthorize'>){
  const {user}=useSession();const[info,setInfo]=useState<OAuthAuthorizeInfo|null>(null);const[loading,setLoading]=useState(false);const[submitting,setSubmitting]=useState(false);const[error,setError]=useState('');
  const raw=route.params||{};const params:OAuthParams|null=raw.client_id&&raw.redirect_uri?{client_id:raw.client_id,redirect_uri:raw.redirect_uri,scope:raw.scope,state:raw.state,response_type:raw.response_type||'code'}:null;
  const load=useCallback(async()=>{if(!params)return setError('缺少 client_id 或 redirect_uri');setLoading(true);setError('');try{setInfo(await oauthApi.info(params))}catch(e){setError(e instanceof Error?e.message:'获取授权信息失败')}finally{setLoading(false)}},[raw.client_id,raw.redirect_uri,raw.scope,raw.state,raw.response_type]);
  useEffect(()=>{void load()},[load]);
  const decide=async(approved:boolean)=>{if(!user)return navigation.navigate('Login');if(!params)return;setSubmitting(true);try{const result=await oauthApi.decide(params,approved);if(!result.redirect_to)throw new Error('服务端未返回回跳地址');await Linking.openURL(result.redirect_to);navigation.goBack()}catch(e){Alert.alert('授权操作失败',e instanceof Error?e.message:'请稍后重试')}finally{setSubmitting(false)}};
  if(loading)return <View style={styles.center}><ActivityIndicator color={colors.ink}/></View>;if(error||!info)return <View style={styles.center}><Text style={styles.error}>{error||'无法完成授权'}</Text><Pressable style={styles.retry} onPress={()=>void load()}><Text style={styles.retryText}>重试</Text></Pressable></View>;
  const logo=resolveAssetUrl(info.app.logo_url);const hasAdmin=info.scopes.some(s=>s.risk==='admin');const hasWrite=info.scopes.some(s=>s.risk==='write');
  return <ScrollView contentContainerStyle={styles.content}><View style={styles.app}>{logo?<Image source={{uri:logo}} style={styles.logo}/>:<View style={styles.logoEmpty}><Text style={styles.initial}>{info.app.name.slice(0,1)}</Text></View>}<View style={{flex:1}}><Text style={styles.name}>{info.app.name}</Text><Text style={styles.desc}>{info.app.description||'申请访问你的编程狗账号数据'}</Text></View></View><View style={[styles.risk,hasAdmin&&styles.danger,hasWrite&&!hasAdmin&&styles.warning]}><Text style={styles.riskText}>{hasAdmin?'该应用申请管理权限，请确认应用可信。':hasWrite?'该应用可以代表你修改数据。':'该应用申请读取以下账号数据。'}</Text></View>{info.reauthorization_required&&<Text style={styles.reauth}>应用新增了权限，需要你重新确认。</Text>}<Text style={styles.heading}>申请的权限</Text>{info.scopes.map(scope=><View key={scope.key} style={styles.scope}><View style={styles.scopeTop}><Text style={styles.scopeName}>{scope.name||scope.key}</Text>{scope.is_new&&<Text style={styles.new}>新增</Text>}<Text style={styles.riskTag}>{scope.risk==='admin'?'管理':scope.risk==='write'?'写入':'只读'}</Text></View><Text style={styles.scopeDesc}>{scope.description||scope.key}</Text></View>)}<Text style={styles.identity}>{user?`将以 ${user.nickname||user.username} 的身份授权`:'请先登录后确认授权'}</Text><View style={styles.actions}><Pressable disabled={submitting} onPress={()=>void decide(false)} style={styles.deny}><Text style={styles.denyText}>拒绝</Text></Pressable><Pressable disabled={submitting} onPress={()=>void decide(true)} style={styles.allow}>{submitting?<ActivityIndicator color={colors.ink}/>:<Text style={styles.allowText}>{user?'允许授权':'登录并授权'}</Text>}</Pressable></View></ScrollView>
}
const styles=StyleSheet.create({center:{flex:1,padding:30,alignItems:'center',justifyContent:'center',backgroundColor:colors.background},content:{padding:20,paddingBottom:40},app:{padding:18,flexDirection:'row',alignItems:'center',gap:13,borderRadius:20,backgroundColor:colors.surface},logo:{width:58,height:58,borderRadius:16},logoEmpty:{width:58,height:58,alignItems:'center',justifyContent:'center',borderRadius:16,backgroundColor:colors.primary},initial:{fontSize:23,fontWeight:'900',color:colors.ink},name:{fontSize:20,fontWeight:'900',color:colors.ink},desc:{marginTop:5,fontSize:12,lineHeight:18,color:colors.muted},risk:{marginTop:14,padding:14,borderRadius:14,backgroundColor:colors.blueSoft},warning:{backgroundColor:'#FFF4D1'},danger:{backgroundColor:'#FFF0F0'},riskText:{fontSize:12,lineHeight:19,fontWeight:'700',color:colors.ink},reauth:{marginTop:10,padding:12,borderRadius:12,color:'#805E00',backgroundColor:'#FFF7DD'},heading:{marginTop:22,marginBottom:10,fontSize:17,fontWeight:'900',color:colors.ink},scope:{marginBottom:9,padding:14,borderRadius:15,backgroundColor:colors.surface},scopeTop:{flexDirection:'row',alignItems:'center',gap:7},scopeName:{flex:1,fontSize:14,fontWeight:'900',color:colors.ink},new:{fontSize:9,fontWeight:'900',color:'#805E00'},riskTag:{fontSize:9,color:colors.subtle},scopeDesc:{marginTop:5,fontSize:11,lineHeight:17,color:colors.muted},identity:{marginTop:16,textAlign:'center',fontSize:11,color:colors.subtle},actions:{marginTop:20,flexDirection:'row',gap:10},deny:{flex:1,height:50,alignItems:'center',justifyContent:'center',borderRadius:14,borderWidth:1,borderColor:colors.border},denyText:{fontWeight:'900',color:colors.ink},allow:{flex:2,height:50,alignItems:'center',justifyContent:'center',borderRadius:14,backgroundColor:colors.primary},allowText:{fontWeight:'900',color:colors.ink},error:{textAlign:'center',color:colors.danger},retry:{marginTop:18,paddingHorizontal:22,height:42,alignItems:'center',justifyContent:'center',borderRadius:12,backgroundColor:colors.primary},retryText:{fontWeight:'900',color:colors.ink}});
