import { useNavigation } from '@react-navigation/native';
import type { NativeStackNavigationProp } from '@react-navigation/native-stack';
import { useEffect, useRef, useState } from 'react';
import { KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { communityApi } from '../api/community';
import { worksApi } from '../api/works';
import { useSession } from '../session/SessionContext';
import { colors } from '../theme';
import type { RootStackParamList } from '../types/navigation';

type Mode='work'|'post';
export function PublishScreen(){
  const navigation=useNavigation<NativeStackNavigationProp<RootStackParamList>>(); const{user}=useSession(); const loadedDraft=useRef(false);
  const[mode,setMode]=useState<Mode>('work'); const[workId,setWorkId]=useState(''); const[title,setTitle]=useState(''); const[content,setContent]=useState(''); const[busy,setBusy]=useState(false); const[message,setMessage]=useState(''); const[error,setError]=useState(''); const[draftState,setDraftState]=useState('');
  useEffect(()=>{if(!user||loadedDraft.current)return;loadedDraft.current=true;void communityApi.getDraft().then(d=>{if(d){setTitle(d.title||'');setContent(d.content||'');setDraftState('已恢复草稿')}}).catch(()=>null)},[user]);
  useEffect(()=>{if(!user||mode!=='post'||!loadedDraft.current||(!title.trim()&&!content.trim()))return;setDraftState('保存中…');const timer=setTimeout(()=>{void communityApi.saveDraft({title,content,category:'discussion'}).then(()=>setDraftState('草稿已保存')).catch(()=>setDraftState('草稿保存失败'))},900);return()=>clearTimeout(timer)},[title,content,mode,user]);
  const submit=async()=>{if(!user){navigation.navigate('Login');return}setBusy(true);setError('');setMessage('');try{if(mode==='work'){if(!/^\d+$/.test(workId.trim()))throw new Error('请输入正确的编程猫作品 ID');const work=await worksApi.publish(workId.trim());setMessage('作品发布成功');navigation.navigate('WorkDetail',{codemaoId:String(work.codemao_work_id),title:work.name})}else{if(title.trim().length<2||content.trim().length<5)throw new Error('标题或正文内容过短');const post=await communityApi.createPost({title:title.trim(),content:content.trim(),category:'discussion'});await communityApi.deleteDraft().catch(()=>null);setTitle('');setContent('');setDraftState('');navigation.navigate('PostDetail',{id:post.id,title:post.title})}}catch(e){setError(e instanceof Error?e.message:'发布失败')}finally{setBusy(false)}};
  return <SafeAreaView style={styles.safe} edges={['top']}><KeyboardAvoidingView style={{flex:1}} behavior={Platform.OS==='ios'?'padding':undefined}><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><Text style={styles.pageTitle}>创作</Text><Text style={styles.subtitle}>把作品和想法分享给社区</Text><View style={styles.switch}>{(['work','post'] as Mode[]).map(value=><Pressable key={value} onPress={()=>{setMode(value);setError('');setMessage('')}} style={[styles.switchItem,mode===value&&styles.switchActive]}><Text style={[styles.switchText,mode===value&&styles.switchTextActive]}>{value==='work'?'发布作品':'发布帖子'}</Text></Pressable>)}</View><View style={styles.card}>{mode==='work'?<><Text style={styles.label}>编程猫作品 ID</Text><TextInput value={workId} onChangeText={setWorkId} keyboardType="number-pad" placeholder="例如：123456789" placeholderTextColor={colors.subtle} style={styles.input}/><Text style={styles.help}>App 会读取作品资料，并按社区审核规则发布。</Text></>:<><View style={styles.labelRow}><Text style={styles.label}>标题</Text><Text style={styles.draft}>{draftState}</Text></View><TextInput value={title} onChangeText={setTitle} maxLength={100} placeholder="清楚地说明你想讨论什么" placeholderTextColor={colors.subtle} style={styles.input}/><Text style={styles.label}>正文</Text><TextInput value={content} onChangeText={setContent} maxLength={10000} multiline textAlignVertical="top" placeholder="分享想法、问题或经验…" placeholderTextColor={colors.subtle} style={styles.textarea}/></>}{!!error&&<Text style={styles.error}>{error}</Text>}{!!message&&<Text style={styles.success}>{message}</Text>}<Pressable disabled={busy} onPress={()=>void submit()} style={[styles.button,busy&&styles.disabled]}><Text style={styles.buttonText}>{!user?'登录后发布':busy?'正在提交…':'确认发布'}</Text></Pressable><Text style={styles.boundary}>启用安全验证时，App 会自动弹出验证挑战并在通过后继续提交。</Text></View></ScrollView></KeyboardAvoidingView></SafeAreaView>
}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:colors.background},content:{padding:18,paddingBottom:35},pageTitle:{fontSize:26,fontWeight:'900',color:colors.ink},subtitle:{marginTop:4,fontSize:12,color:colors.muted},switch:{height:46,marginTop:18,padding:4,flexDirection:'row',borderRadius:14,backgroundColor:'#E8ECF2'},switchItem:{flex:1,alignItems:'center',justifyContent:'center',borderRadius:11},switchActive:{backgroundColor:colors.surface},switchText:{fontSize:13,fontWeight:'700',color:colors.muted},switchTextActive:{color:colors.ink},card:{marginTop:14,padding:19,borderRadius:22,backgroundColor:colors.surface},labelRow:{flexDirection:'row',justifyContent:'space-between'},label:{marginBottom:8,fontSize:13,fontWeight:'800',color:colors.ink},draft:{fontSize:10,color:colors.subtle},input:{height:50,marginBottom:15,paddingHorizontal:14,borderRadius:14,borderWidth:1,borderColor:colors.border,fontSize:15,color:colors.ink},textarea:{minHeight:180,padding:14,borderRadius:14,borderWidth:1,borderColor:colors.border,fontSize:15,lineHeight:23,color:colors.ink},help:{marginTop:-6,fontSize:11,lineHeight:17,color:colors.subtle},error:{marginTop:14,color:colors.danger,fontSize:12},success:{marginTop:14,color:'#23844E',fontSize:12},button:{height:50,marginTop:20,alignItems:'center',justifyContent:'center',borderRadius:14,backgroundColor:colors.primary},buttonText:{fontSize:15,fontWeight:'900',color:colors.ink},disabled:{opacity:.55},boundary:{marginTop:12,fontSize:10,lineHeight:16,color:colors.subtle}});
