import { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, Alert, FlatList, Pressable, StyleSheet, Text, View } from 'react-native';
import type { NativeStackScreenProps } from '@react-navigation/native-stack';
import { communityApi } from '../api/community';
import { worksApi } from '../api/works';
import { colors } from '../theme';
import type { RootStackParamList } from '../types/navigation';
import type { Work } from '../types/work';

export function StudioSubmitScreen({route,navigation}:NativeStackScreenProps<RootStackParamList,'StudioSubmit'>){const [items,setItems]=useState<Work[]>([]);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState<string|null>(null);const load=useCallback(async()=>{try{const data=await worksApi.mine({page:1,pageSize:50});setItems((data.list||[]).filter(w=>(w as Work & {status?:string}).status==='published'));}finally{setLoading(false)}},[]);useEffect(()=>{void load()},[load]);const submit=async(work:Work)=>{setBusy(work.codemao_work_id);try{await communityApi.submitStudioWork(route.params.id,work.codemao_work_id);Alert.alert('投稿已提交','请等待工作室管理员审核',[{text:'完成',onPress:()=>navigation.goBack()}]);}catch(e){Alert.alert('投稿失败',e instanceof Error?e.message:'请稍后重试')}finally{setBusy(null)}};if(loading)return <View style={styles.center}><ActivityIndicator color={colors.ink}/></View>;return <FlatList data={items} keyExtractor={w=>String(w.id)} contentContainerStyle={styles.content} ListEmptyComponent={<Text style={styles.empty}>没有可投稿的已发布作品</Text>} renderItem={({item})=><View style={styles.item}><View style={{flex:1}}><Text style={styles.name}>{item.name}</Text><Text style={styles.id}>#{item.codemao_work_id}</Text></View><Pressable disabled={!!busy} style={styles.button} onPress={()=>void submit(item)}>{busy===item.codemao_work_id?<ActivityIndicator color={colors.ink}/>:<Text style={styles.buttonText}>投稿</Text>}</Pressable></View>}/>}
const styles=StyleSheet.create({center:{flex:1,alignItems:'center',justifyContent:'center'},content:{padding:16,flexGrow:1},item:{marginBottom:10,padding:15,flexDirection:'row',alignItems:'center',borderRadius:17,backgroundColor:colors.surface},name:{fontSize:14,fontWeight:'900',color:colors.ink},id:{marginTop:4,fontSize:10,color:colors.subtle},button:{minWidth:70,height:38,alignItems:'center',justifyContent:'center',borderRadius:11,backgroundColor:colors.primary},buttonText:{fontWeight:'900',color:colors.ink},empty:{padding:60,textAlign:'center',color:colors.subtle}});
