import { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import type { NativeStackScreenProps } from '@react-navigation/native-stack';
import { communityApi } from '../api/community';
import { colors } from '../theme';
import type { RootStackParamList } from '../types/navigation';
type Member=Awaited<ReturnType<typeof communityApi.pendingStudioMembers>>[number];type PendingWork=Awaited<ReturnType<typeof communityApi.pendingStudioWorks>>[number];
export function StudioManageScreen({route}:NativeStackScreenProps<RootStackParamList,'StudioManage'>){const id=route.params.id;const[members,setMembers]=useState<Member[]>([]);const[works,setWorks]=useState<PendingWork[]>([]);const[loading,setLoading]=useState(true);const[busy,setBusy]=useState('');const load=useCallback(async()=>{try{const[m,w]=await Promise.all([communityApi.pendingStudioMembers(id),communityApi.pendingStudioWorks(id)]);setMembers(m||[]);setWorks(w||[])}catch(e){Alert.alert('管理数据加载失败',e instanceof Error?e.message:'请稍后重试')}finally{setLoading(false)}},[id]);useEffect(()=>{void load()},[load]);const reviewMember=async(item:Member,action:'approve'|'reject')=>{setBusy(`m${item.id}`);try{await communityApi.reviewStudioMember(id,item.id,action);setMembers(v=>v.filter(x=>x.id!==item.id))}catch(e){Alert.alert('审核失败',e instanceof Error?e.message:'请稍后重试')}finally{setBusy('')}};const reviewWork=async(item:PendingWork,action:'approve'|'reject')=>{setBusy(`w${item.id}`);try{await communityApi.reviewStudioWork(id,item.id,action);setWorks(v=>v.filter(x=>x.id!==item.id))}catch(e){Alert.alert('审核失败',e instanceof Error?e.message:'请稍后重试')}finally{setBusy('')}};if(loading)return <View style={styles.center}><ActivityIndicator color={colors.ink}/></View>;return <ScrollView contentContainerStyle={styles.content}><Text style={styles.heading}>成员申请</Text>{members.length?members.map(item=><ReviewRow key={item.id} title={item.user?.nickname||item.nickname||item.user?.username||item.username||'社区成员'} busy={busy===`m${item.id}`} approve={()=>void reviewMember(item,'approve')} reject={()=>void reviewMember(item,'reject')}/>):<Text style={styles.empty}>暂无待审核成员</Text>}<Text style={styles.heading}>作品投稿</Text>{works.length?works.map(item=><ReviewRow key={item.id} title={item.work?.name||item.name||`作品 #${item.codemao_work_id||item.id}`} busy={busy===`w${item.id}`} approve={()=>void reviewWork(item,'approve')} reject={()=>void reviewWork(item,'reject')}/>):<Text style={styles.empty}>暂无待审核作品</Text>}</ScrollView>}
function ReviewRow({title,busy,approve,reject}:{title:string;busy:boolean;approve:()=>void;reject:()=>void}){return <View style={styles.row}><Text numberOfLines={2} style={styles.title}>{title}</Text>{busy?<ActivityIndicator color={colors.ink}/>:<View style={styles.actions}><Pressable onPress={reject} style={styles.reject}><Text style={styles.rejectText}>拒绝</Text></Pressable><Pressable onPress={approve} style={styles.approve}><Text style={styles.approveText}>通过</Text></Pressable></View>}</View>}
const styles=StyleSheet.create({center:{flex:1,alignItems:'center',justifyContent:'center'},content:{padding:16,paddingBottom:40},heading:{marginVertical:14,fontSize:18,fontWeight:'900',color:colors.ink},row:{marginBottom:10,padding:15,flexDirection:'row',alignItems:'center',gap:12,borderRadius:17,backgroundColor:colors.surface},title:{flex:1,fontWeight:'800',color:colors.ink},actions:{flexDirection:'row',gap:7},approve:{paddingHorizontal:13,height:36,alignItems:'center',justifyContent:'center',borderRadius:10,backgroundColor:colors.primary},approveText:{fontSize:12,fontWeight:'900',color:colors.ink},reject:{paddingHorizontal:13,height:36,alignItems:'center',justifyContent:'center',borderRadius:10,backgroundColor:'#FFF0F0'},rejectText:{fontSize:12,fontWeight:'900',color:colors.danger},empty:{padding:22,textAlign:'center',borderRadius:15,color:colors.subtle,backgroundColor:colors.surface}});
