import { Ionicons } from '@expo/vector-icons';
import type { NativeStackScreenProps } from '@react-navigation/native-stack';
import { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, Image, Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from 'react-native';
import { resolveAssetUrl } from '../api/client';
import { communityApi } from '../api/community';
import { userApi } from '../api/user';
import { worksApi } from '../api/works';
import { WorkCard } from '../components/WorkCard';
import { useSession } from '../session/SessionContext';
import { colors } from '../theme';
import type { Post } from '../types/community';
import type { RootStackParamList } from '../types/navigation';
import type { PublicUser } from '../types/user';
import type { Work } from '../types/work';

type Tab = 'works'|'posts'|'followers'|'following';
export function UserProfileScreen({route,navigation}:NativeStackScreenProps<RootStackParamList,'UserProfile'>) {
  const {user:me}=useSession(); const id=route.params.codemaoId; const own=String(me?.codemao_user_id||'')===id;
  const [profile,setProfile]=useState<PublicUser|null>(null); const [works,setWorks]=useState<Work[]>([]); const [posts,setPosts]=useState<Post[]>([]);
  const [followers,setFollowers]=useState<PublicUser[]>([]); const [followingUsers,setFollowingUsers]=useState<PublicUser[]>([]); const [tab,setTab]=useState<Tab>('works');
  const [following,setFollowing]=useState(false); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(false); const [refreshing,setRefreshing]=useState(false); const [error,setError]=useState('');
  const load=useCallback(async()=>{try{setError('');const [p,w,postPage,fans,followed,followState]=await Promise.all([userApi.publicProfile(id),worksApi.byUser(id),communityApi.postsByCodemaoUser(id),userApi.followers(id),userApi.following(id),!own&&me?userApi.checkFollow(id).catch(()=>null):Promise.resolve(null)]);setProfile(p);setWorks(w.list||[]);setPosts(postPage.list||[]);setFollowers(fans.list||[]);setFollowingUsers(followed.list||[]);setFollowing(!!followState?.isFollowing);}catch(e){setError(e instanceof Error?e.message:'加载失败');}finally{setLoading(false);setRefreshing(false);}},[id,me,own]);
  useEffect(()=>{void load();},[load]);
  const toggle=async()=>{if(!me)return navigation.navigate('Login');setBusy(true);try{following?await userApi.unfollow(id):await userApi.follow(id);setFollowing((value)=>!value);setProfile((value)=>value?{...value,follower_count:Math.max(0,(value.follower_count||0)+(following?-1:1))}:value);}catch(e){setError(e instanceof Error?e.message:'操作失败');}finally{setBusy(false);}};
  if(loading)return <View style={styles.center}><ActivityIndicator color={colors.ink}/></View>;
  if(!profile)return <View style={styles.center}><Text style={styles.error}>{error||'用户不存在'}</Text></View>;
  const avatar=resolveAssetUrl(profile.avatar); const name=profile.nickname||profile.username;
  return <ScrollView style={styles.safe} contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>{setRefreshing(true);void load();}}/>}>
    <View style={styles.profile}>{avatar?<Image source={{uri:avatar}} style={styles.avatar}/>:<View style={styles.avatarEmpty}><Text style={styles.initial}>{name.slice(0,1).toUpperCase()}</Text></View>}<Text style={styles.name}>{name}</Text><Text style={styles.doing}>{profile.doing||profile.bio||'这位创作者还没有填写简介'}</Text><View style={styles.stats}><Stat value={profile.work_count||works.length} label="作品"/><Stat value={profile.follower_count||followers.length} label="粉丝"/><Stat value={profile.following_count||followingUsers.length} label="关注"/></View>{own?<Pressable style={styles.outline} onPress={()=>navigation.navigate('EditProfile')}><Text style={styles.outlineText}>编辑资料</Text></Pressable>:<Pressable disabled={busy} style={[styles.follow,following&&styles.following]} onPress={()=>void toggle()}>{busy?<ActivityIndicator color={colors.ink}/>:<Text style={styles.followText}>{following?'已关注':'关注'}</Text>}</Pressable>}{!!error&&<Text style={styles.error}>{error}</Text>}</View>
    <View style={styles.tabs}><TabButton active={tab==='works'} label="作品" count={works.length} onPress={()=>setTab('works')}/><TabButton active={tab==='posts'} label="帖子" count={posts.length} onPress={()=>setTab('posts')}/><TabButton active={tab==='followers'} label="粉丝" count={profile.follower_count||followers.length} onPress={()=>setTab('followers')}/><TabButton active={tab==='following'} label="关注" count={profile.following_count||followingUsers.length} onPress={()=>setTab('following')}/></View>
    {tab==='works' && (works.length?<View style={styles.grid}>{works.map((work)=><WorkCard key={work.id} compact work={work} onPress={()=>navigation.navigate('WorkDetail',{codemaoId:work.codemao_work_id,title:work.name})}/>)}</View>:<Empty text="还没有公开作品"/>)}
    {tab==='posts' && (posts.length?<View style={styles.list}>{posts.map((post)=><Pressable key={post.id} onPress={()=>navigation.navigate('PostDetail',{id:post.id,title:post.title})} style={styles.post}><View style={styles.postIcon}><Ionicons name="chatbubble-ellipses-outline" size={18} color={colors.ink}/></View><View style={styles.grow}><Text numberOfLines={2} style={styles.postTitle}>{post.title}</Text><Text style={styles.meta}>{post.view_count||0} 阅读 · {post.reply_count||post.comment_count||0} 回复 · {post.like_count||0} 点赞</Text></View><Ionicons name="chevron-forward" size={17} color={colors.subtle}/></Pressable>)}</View>:<Empty text="还没有公开帖子"/>)}
    {tab==='followers' && <UserList users={followers} onOpen={(codemaoId)=>navigation.push('UserProfile',{codemaoId})} empty="还没有粉丝"/>}
    {tab==='following' && <UserList users={followingUsers} onOpen={(codemaoId)=>navigation.push('UserProfile',{codemaoId})} empty="还没有关注用户"/>}
  </ScrollView>;
}
function Stat({value,label}:{value:number;label:string}){return <View style={styles.stat}><Text style={styles.statValue}>{value}</Text><Text style={styles.statLabel}>{label}</Text></View>}
function TabButton({active,label,count,onPress}:{active:boolean;label:string;count:number;onPress:()=>void}){return <Pressable onPress={onPress} style={[styles.tab,active&&styles.tabActive]}><Text numberOfLines={1} style={[styles.tabText,active&&styles.tabTextActive]}>{label} {count}</Text></Pressable>}
function Empty({text}:{text:string}){return <Text style={styles.empty}>{text}</Text>}
function UserList({users,onOpen,empty}:{users:PublicUser[];onOpen:(id:string)=>void;empty:string}){if(!users.length)return <Empty text={empty}/>;return <View style={styles.list}>{users.map((user)=>{const avatar=resolveAssetUrl(user.avatar);const name=user.nickname||user.username;return <Pressable key={String(user.codemao_user_id)} onPress={()=>user.codemao_user_id&&onOpen(String(user.codemao_user_id))} style={styles.user}>{avatar?<Image source={{uri:avatar}} style={styles.userAvatar}/>:<View style={styles.userAvatarEmpty}><Text style={styles.userInitial}>{name.slice(0,1).toUpperCase()}</Text></View>}<View style={styles.grow}><Text style={styles.userName}>{name}</Text><Text numberOfLines={1} style={styles.meta}>{user.bio||`${user.work_count||0} 个作品 · ${user.follower_count||0} 位粉丝`}</Text></View><Ionicons name="chevron-forward" size={17} color={colors.subtle}/></Pressable>})}</View>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:colors.background},center:{flex:1,alignItems:'center',justifyContent:'center',backgroundColor:colors.background},content:{padding:16,paddingBottom:50},profile:{alignItems:'center',padding:22,borderRadius:22,backgroundColor:colors.surface},avatar:{width:76,height:76,borderRadius:24},avatarEmpty:{width:76,height:76,alignItems:'center',justifyContent:'center',borderRadius:24,backgroundColor:colors.ink},initial:{fontSize:27,fontWeight:'900',color:'#FFF'},name:{marginTop:13,fontSize:22,fontWeight:'900',color:colors.ink},doing:{marginTop:7,textAlign:'center',lineHeight:20,color:colors.muted},stats:{width:'100%',marginTop:18,flexDirection:'row'},stat:{flex:1,alignItems:'center'},statValue:{fontSize:17,fontWeight:'900',color:colors.ink},statLabel:{fontSize:10,color:colors.subtle},follow:{width:'100%',height:46,marginTop:18,alignItems:'center',justifyContent:'center',borderRadius:14,backgroundColor:colors.primary},following:{backgroundColor:colors.blueSoft},followText:{fontWeight:'900',color:colors.ink},outline:{width:'100%',height:46,marginTop:18,alignItems:'center',justifyContent:'center',borderRadius:14,borderWidth:1,borderColor:colors.border},outlineText:{fontWeight:'800',color:colors.ink},tabs:{height:50,marginTop:14,paddingHorizontal:3,flexDirection:'row',alignItems:'stretch',borderRadius:16,backgroundColor:colors.surface},tab:{flex:1,alignItems:'center',justifyContent:'center',borderBottomWidth:3,borderBottomColor:'transparent'},tabActive:{borderBottomColor:colors.primary},tabText:{fontSize:11,color:colors.muted},tabTextActive:{fontWeight:'900',color:colors.ink},grid:{marginTop:16,flexDirection:'row',flexWrap:'wrap',justifyContent:'space-between'},list:{marginTop:16,overflow:'hidden',borderRadius:18,backgroundColor:colors.surface},post:{minHeight:76,padding:13,flexDirection:'row',alignItems:'center',gap:11,borderBottomWidth:1,borderBottomColor:colors.border},postIcon:{width:38,height:38,alignItems:'center',justifyContent:'center',borderRadius:12,backgroundColor:colors.primarySoft},grow:{flex:1},postTitle:{color:colors.ink,fontSize:14,lineHeight:20,fontWeight:'800'},meta:{marginTop:4,color:colors.subtle,fontSize:11},user:{minHeight:70,padding:12,flexDirection:'row',alignItems:'center',gap:11,borderBottomWidth:1,borderBottomColor:colors.border},userAvatar:{width:44,height:44,borderRadius:14},userAvatarEmpty:{width:44,height:44,alignItems:'center',justifyContent:'center',borderRadius:14,backgroundColor:colors.ink},userInitial:{color:'#FFF',fontWeight:'900'},userName:{color:colors.ink,fontSize:14,fontWeight:'800'},empty:{paddingVertical:60,textAlign:'center',color:colors.subtle},error:{marginTop:10,color:colors.danger}});
