import { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, FlatList, Image, Pressable, RefreshControl, StyleSheet, Text, View } from 'react-native';
import type { NativeStackScreenProps } from '@react-navigation/native-stack';
import { resolveAssetUrl } from '../api/client';
import { userApi } from '../api/user';
import { worksApi } from '../api/works';
import { WorkCard } from '../components/WorkCard';
import { useSession } from '../session/SessionContext';
import { colors } from '../theme';
import type { RootStackParamList } from '../types/navigation';
import type { PublicUser } from '../types/user';
import type { Work } from '../types/work';

export function UserProfileScreen({ route, navigation }: NativeStackScreenProps<RootStackParamList, 'UserProfile'>) {
  const { user: me } = useSession(); const id = route.params.codemaoId;
  const [profile,setProfile]=useState<PublicUser|null>(null); const [works,setWorks]=useState<Work[]>([]);
  const [following,setFollowing]=useState(false); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(false); const [refreshing,setRefreshing]=useState(false); const [error,setError]=useState('');
  const own = String(me?.codemao_user_id || '') === id;
  const load=useCallback(async()=>{try{setError('');const [p,w,f]=await Promise.all([userApi.publicProfile(id),worksApi.byUser(id),!own&&me?userApi.checkFollow(id).catch(()=>null):Promise.resolve(null)]);setProfile(p);setWorks(w.list||[]);setFollowing(!!f?.isFollowing);}catch(e){setError(e instanceof Error?e.message:'加载失败');}finally{setLoading(false);setRefreshing(false);}},[id,me,own]);
  useEffect(()=>{void load();},[load]);
  const toggle=async()=>{if(!me)return navigation.navigate('Login');setBusy(true);try{following?await userApi.unfollow(id):await userApi.follow(id);setFollowing(v=>!v);setProfile(p=>p?{...p,follower_count:Math.max(0,(p.follower_count||0)+(following?-1:1))}:p);}catch(e){setError(e instanceof Error?e.message:'操作失败');}finally{setBusy(false);}};
  if(loading)return <View style={styles.center}><ActivityIndicator color={colors.ink}/></View>;
  if(!profile)return <View style={styles.center}><Text style={styles.error}>{error||'用户不存在'}</Text></View>;
  const avatar=resolveAssetUrl(profile.avatar); const name=profile.nickname||profile.username;
  return <FlatList data={works} numColumns={2} keyExtractor={w=>String(w.id)} columnWrapperStyle={styles.row} contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>{setRefreshing(true);void load();}}/>} ListHeaderComponent={<View><View style={styles.profile}>{avatar?<Image source={{uri:avatar}} style={styles.avatar}/>:<View style={styles.avatarEmpty}><Text style={styles.initial}>{name.slice(0,1)}</Text></View>}<Text style={styles.name}>{name}</Text><Text style={styles.doing}>{profile.doing||profile.bio||'这位创作者还没有填写简介'}</Text><View style={styles.stats}><Stat value={profile.work_count||works.length} label="作品"/><Pressable style={styles.stat} onPress={()=>navigation.navigate('Connections',{codemaoId:id,mode:'followers',title:'粉丝'})}><Text style={styles.statValue}>{profile.follower_count||0}</Text><Text style={styles.statLabel}>粉丝</Text></Pressable><Pressable style={styles.stat} onPress={()=>navigation.navigate('Connections',{codemaoId:id,mode:'following',title:'关注'})}><Text style={styles.statValue}>{profile.following_count||0}</Text><Text style={styles.statLabel}>关注</Text></Pressable></View>{own?<Pressable style={styles.outline} onPress={()=>navigation.navigate('EditProfile')}><Text style={styles.outlineText}>编辑资料</Text></Pressable>:<Pressable disabled={busy} style={[styles.follow,following&&styles.following]} onPress={()=>void toggle()}>{busy?<ActivityIndicator color={colors.ink}/>:<Text style={styles.followText}>{following?'已关注':'关注'}</Text>}</Pressable>}{!!error&&<Text style={styles.error}>{error}</Text>}</View><Text style={styles.heading}>TA 的作品</Text></View>} ListEmptyComponent={<Text style={styles.empty}>还没有公开作品</Text>} renderItem={({item})=><WorkCard compact work={item} onPress={()=>navigation.navigate('WorkDetail',{codemaoId:item.codemao_work_id,title:item.name})}/>}/>;
}
function Stat({value,label}:{value:number;label:string}){return <View style={styles.stat}><Text style={styles.statValue}>{value}</Text><Text style={styles.statLabel}>{label}</Text></View>}
const styles=StyleSheet.create({center:{flex:1,alignItems:'center',justifyContent:'center',backgroundColor:colors.background},content:{padding:16,paddingBottom:36,flexGrow:1},row:{justifyContent:'space-between'},profile:{alignItems:'center',padding:22,borderRadius:22,backgroundColor:colors.surface},avatar:{width:76,height:76,borderRadius:24},avatarEmpty:{width:76,height:76,alignItems:'center',justifyContent:'center',borderRadius:24,backgroundColor:colors.ink},initial:{fontSize:27,fontWeight:'900',color:'#fff'},name:{marginTop:13,fontSize:22,fontWeight:'900',color:colors.ink},doing:{marginTop:7,textAlign:'center',lineHeight:20,color:colors.muted},stats:{width:'100%',marginTop:18,flexDirection:'row'},stat:{flex:1,alignItems:'center'},statValue:{fontSize:17,fontWeight:'900',color:colors.ink},statLabel:{fontSize:10,color:colors.subtle},follow:{width:'100%',height:46,marginTop:18,alignItems:'center',justifyContent:'center',borderRadius:14,backgroundColor:colors.primary},following:{backgroundColor:colors.blueSoft},followText:{fontWeight:'900',color:colors.ink},outline:{width:'100%',height:46,marginTop:18,alignItems:'center',justifyContent:'center',borderRadius:14,borderWidth:1,borderColor:colors.border},outlineText:{fontWeight:'800',color:colors.ink},heading:{marginVertical:18,fontSize:18,fontWeight:'900',color:colors.ink},empty:{padding:50,textAlign:'center',color:colors.subtle},error:{marginTop:10,color:colors.danger}});
